default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: instagram-challenge_development

test:
  <<: *default
  database: instagram-challenge_test

production:
  <<: *default
  database: instagram-challenge_production
  username: instagram-challenge
  password: <%= ENV['INSTAGRAM-CHALLENGE_DATABASE_PASSWORD'] %>
